{
  "category": "Exceptions",
  "name": "THROW",
  "tests": [
    {
      "script": "37",
      "steps": [
        {
          "actions": [
            "StepInto"
          ],
          "result": {
            "state": "Fault"
          }
        }
      ]
    }
  ]
}